<a href="https://colab.research.google.com/github/ayberkcorp/cap4630-artificial_intelligence/blob/master/MatrixMultiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix Multiplication
---
Two matrices can be multiplied if the number of columns of the first matrix is equal to the number of rows of the second matrix. In this case, we say the two matrices are **compatible** and the resultant matrix, called the **matrix product**, has the number of rows of the first and the number of columns of the second matrix.

# Multiplicative Compatibility of Matrices
---
Two matrices $A$ and $B$ of dimensions $m \times n$ and $p \times q$, respectively, are *compatible* if and only if $n = p$ or $m = q$.

### Generating a Matrix Multiplication Chain:
The function generate_matrices() shown in the code cell below was used to generate the following matrix multiplication chain:

$\begin{bmatrix}
  7 & 2 & 1 & 6 & 1 \\
  0 & 2 & 7 & 9 & 1 \\
  5 & 4 & 5 & 0 & 8
\end{bmatrix} \begin{bmatrix}
  7 & 9 & 7 \\
  4 & 2 & 1 \\
  6 & 8 & 4 \\
  7 & 3 & 2 \\
  4 & 6 & 6
\end{bmatrix} \begin{bmatrix}
  5 & 7 & 9 \\
  0 & 4 & 3 \\
  4 & 4 & 2
\end{bmatrix} \begin{bmatrix}
  9 & 3 & 8 & 7 & 9 \\
  1 & 4 & 4 & 6 & 4 \\
  4 & 2 & 2 & 0 & 9
\end{bmatrix} \begin{bmatrix}
  1 \\
  1 \\
  0 \\
  5 \\
  0
\end{bmatrix}$

This chain is valid because each consecutive pair of matrices are compatible.

In [0]:
import numpy as np
from random import randint

# Returns a nonempty list of validly multipliable random matrices.
def generate_matrices():
  matrices = []

  # The list can have a random number of matrices up to and including 10.
  num_matrices = randint(1, 10)

  # Each matrix is 2D and randomly shaped inclusively up to 5 elements
  # per axis.  The list does not include empty matrices.
  m, n = randint(1, 5), randint(1,5)

  for i in range(num_matrices):
    # The entries in each matrix are random integers from [0-9].
    matrices.append(np.random.randint(0, 10, (m, n)))
    m = n
    n = randint(1, 5)

  return matrices

# Optional: remove "# "  on the line below to see the matrices generated.
# print(generate_matrices())

### Finding the Matrix Product of a Chain:
The function multiply_matrices() shown in the code cell below produces the following matrix product for the chain presented earlier:

$\begin{bmatrix}
  7 & 2 & 1 & 6 & 1 \\
  0 & 2 & 7 & 9 & 1 \\
  5 & 4 & 5 & 0 & 8
\end{bmatrix} \begin{bmatrix}
  7 & 9 & 7 \\
  4 & 2 & 1 \\
  6 & 8 & 4 \\
  7 & 3 & 2 \\
  4 & 6 & 6
\end{bmatrix} \begin{bmatrix}
  5 & 7 & 9 \\
  0 & 4 & 3 \\
  4 & 4 & 2
\end{bmatrix} \begin{bmatrix}
  9 & 3 & 8 & 7 & 9 \\
  1 & 4 & 4 & 6 & 4 \\
  4 & 2 & 2 & 0 & 9
\end{bmatrix} \begin{bmatrix}
  1 \\
  1 \\
  0 \\
  5 \\
  0
\end{bmatrix} = \begin{bmatrix}
  98668 \\
  95532 \\
  119000
\end{bmatrix}$

In [0]:
# A custom exception class.
class IncompatibleMatricesError(Exception):
  """Raised when trying to multiply two matrices
  that have incompatible dimensions.
  """
  pass

# Returns the matrix product of a matrix multiplication chain.
def multiply_matrices(matrices):
  try:
    matrix_product = matrices[0]
    for i in range(len(matrices) - 1):
      if matrix_product.shape[1] != matrices[i + 1].shape[0]:
        raise IncompatibleMatricesError
      matrix_product = np.matmul(matrix_product, matrices[i + 1])
    return matrix_product
  except IncompatibleMatricesError:
    return "The matrices in slots %d and %d are incompatible." % (i, i + 1)
  except IndexError:
    return "The list is empty."

In [63]:
# Test Cases for multiply_matrices() above:

# The chain that was presented earlier.
matrices_1 = [np.array([[7, 2, 1, 6, 1],
                       [0, 2, 7, 9, 1],
                       [5, 4, 5, 0, 8]]),
             np.array([[7, 9, 7],
                       [4, 2, 1],
                       [6, 8, 4],
                       [7, 3, 2],
                       [4, 6, 6]]),
             np.array([[5, 7, 9],
                       [0, 4, 3],
                       [4, 4, 2]]),
             np.array([[9, 3, 8, 7, 9],
                       [1, 4, 4, 6, 4],
                       [4, 2, 2, 0, 9]]),
             np.array([[1],
                       [1],
                       [0],
                       [5],
                       [0]])]

# Same as matrices_1, but with an incompatible pair.
matrices_2 = [np.array([[7, 2, 1, 6, 1],
                        [0, 2, 7, 9, 1],
                        [5, 4, 5, 0, 8]]),
              np.array([[7, 9, 7],
                        [4, 2, 1],
                        [6, 8, 4],
                        [7, 3, 2],
                        [4, 6, 6]]),
              np.array([[5, 7, 9],
                        [0, 4, 3],
                        [4, 4, 2],
                        [3, 3, 1]]),  # <--- Put an extra row here.
              np.array([[9, 3, 8, 7, 9],
                        [1, 4, 4, 6, 4],
                        [4, 2, 2, 0, 9]]),
              np.array([[1],
                        [1],
                        [0],
                        [5],
                        [0]])]

# An empty list.
matrices_3 = []

# A list with exactly one matrix.
matrices_4 = [np.array([[4, 1, 9, 3],
                        [1, 6, 9, 0],
                        [2, 2, 1, 9]])]

# Testing these lists of matrices.
print("Output for matrices_1:")
print(multiply_matrices(matrices_1))
print("\nOutput for matrices_2:")
print(multiply_matrices(matrices_2))
print("\nOutput for matrices_3:")
print(multiply_matrices(matrices_3))
print("\nOutput for matrices_4:")
print(multiply_matrices(matrices_4))

Output for matrices_1:
[[ 98668]
 [ 95532]
 [119000]]

Output for matrices_2:
The matrices in slots 1 and 2 are incompatible.

Output for matrices_3:
The list is empty.

Output for matrices_4:
[[4 1 9 3]
 [1 6 9 0]
 [2 2 1 9]]
