<a href="https://colab.research.google.com/github/ayberkcorp/cap4630-artificial_intelligence/blob/master/HW_4/Problem2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Max pooling

### Implement maxpooling2d():

In [0]:
import numpy as np

def maxpooling2d(input_mat, s):
  if((s, s) > np.shape(input_mat)):
    print("Error: window is larger than input_mat")
    return []

  m = np.shape(input_mat)[0]
  n = np.shape(input_mat)[1]
  output_mat_s = int(m / s)
  output_mat = np.zeros((output_mat_s, output_mat_s))

  for i in range(0, m, s):
    for j in range(0, n, s):
      for i_w in range(s):
        for j_w in range(s):
          # If matrix is out of bounds, we pass that iteration
          try:
            I_o, J_o = int(i / s), int(j / s)
            I_i, J_i = (int(i) + i_w), (int(j) + j_w)
            output_mat[I_o][J_o] = max(output_mat[I_o][J_o], input_mat[I_i][J_i])
          except:
            pass

return output_mat

### Testing:

In [5]:
import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
  # output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")

[[4. 2.]
 [2. 4.]]
Correct output!
[[4. 2. 5.]
 [2. 4. 5.]
 [1. 3. 2.]]
Correct output!
